

---Q1. What is the total revenue generated by male vs. female customers?---
select gender , sum(purchase_amount) as revenue from customer
group by gender

---Q2. Which customer used a discount but still spent more than the average purchase amount?---
select customer_id, purchase_amount from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)


---Q3. Which are top 5 products with the highest average review rating?---
select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Avearage Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;


---Q4. Compare the avarage purchase amounts between Standard and Express Shipping?---
select shipping_type, ROUND(AVG(purchase_amount),2) from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type


---Q.5 Do subscribed customers spent more? Compare average speed and total revenue between subscribed and non subscribed---
select subscription_status, COUNT(customer_id) as total_customers, 
AVG(Purchase_Amount) as avg_spend, SUM(Purchase_Amount) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc


---Q.6 which 5 products have the highest percentage of purchaes with discount applied?---
select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*), 2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;


---Q7. Segment Customers into new, returning and loayl based on their total no. of prevoius purchases, and show the count of each segment.
with customer_type as (
select customer_id, previous_purchases, 
CASE 
    WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END As customer_segment
from customer
) 
select customer_segment, COUNT(*) as "NO of Customers" from customer_type
group by customer_segment



---Q8. Which is 3 most purchased products within each category?
with item_counts as (
 select category, item_purchased, COUNT(*) as total_orders,
ROW_NUMBER() over(partition by category order by count(*) DESC) as item_rank
 from customer
 group by category, item_purchased
)
select category, item_purchased, total_orders
from item_counts
where item_rank <=3


---Q9. Are customers who are repeat buyers (more than 5 previous purchases). also likely to subscribe?---
select subscription_status,
count (customer_id) as repeat_buyers from customer
where previous_purchases > 5
group by subscription_status


---Q10. What is the revnue contribution of each age group?---
select age_group, SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;










